name: No bare except

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  no-bare-except:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run bare-except check
        run: |
          python tools/check_no_bare_except.py \
            --paths \
              vop_interwoven/pipeline.py \
              vop_interwoven/revit \
              vop_interwoven/core \
            --whitelist tools/bare_except_whitelist.txt
