name: No bare except

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  no-bare-except:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run bare-except check (pwsh)
        shell: pwsh
        run: |
          ./tools/check_no_bare_except.ps1 `
            -Paths @(
              "vop_interwoven/pipeline.py",
              "vop_interwoven/revit",
              "vop_interwoven/core"
            ) `
            -Whitelist "tools/bare_except_whitelist.txt"
